# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 02:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ebuy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to=ebuy.models.get_image_filename)),
                ('img2', models.ImageField(upload_to=ebuy.models.get_image_filename)),
                ('img3', models.ImageField(upload_to=ebuy.models.get_image_filename)),
                ('title', models.CharField(default='', max_length=30)),
                ('description', models.TextField()),
                ('availability', models.PositiveIntegerField(blank=True, default='10')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('category', models.CharField(choices=[(b'DEC', b'Decor'), (b'PIL', b'Pillows'), (b'FUR', b'Furnitures'), (b'PET', b'PetProduct'), (b'GIF', b'Gifts'), (b'CER', b'Ceramics')], max_length=3)),
                ('size', models.CharField(default='One Size', max_length=30)),
                ('color', models.CharField(default='', max_length=30)),
                ('content_type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SharedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=ebuy.models.get_shared_img_path)),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('content_type', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('age', models.CharField(default='20', max_length=3)),
                ('image', models.FileField(blank=True, default='default.jpg', upload_to='profile')),
                ('content_type', models.CharField(default='', max_length=50)),
                ('order', models.ManyToManyField(blank=True, related_name='order', to='ebuy.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishList', models.ManyToManyField(blank=True, related_name='wishList', to='ebuy.Product')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ebuy.Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bag',
            name='itemsInBag',
            field=models.ManyToManyField(blank=True, related_name='itemsInBag', to='ebuy.Product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amount',
            name='bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebuy.Bag'),
        ),
        migrations.AddField(
            model_name='amount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebuy.Product'),
        ),
    ]
